config/routes.rb
Alpha::Application.routes.draw do
  
  match '/login' => 'sessions#new', :as => 'login'
  match '/logout' => 'sessions#destroy', :as => 'logout'
  post '/sessions' => 'sessions#create'
  
  resources :templates, :only => [:index]
  
  constraints :domain => Config::DOMAIN, :subdomain => Config::RESERVED_SUBDOMAINS_REGEX do
    resources :users
    resources :sites, :only => [:new, :create]
    root :to => 'main#index'
    match '*invalidpath' => redirect("")
  end
  
  get 'new/*slug' => 'pages#new', :as => 'new_page'
  get 'edit/(*slug)' => 'pages#edit', :as => 'edit_page'
  post 'update/(*slug)' => 'pages#update', :as => 'update_page'
  get '(*slug)' => 'pages#show', :as => 'show_page'
  put '*slug' => 'pages#create'
    
  

end

app/models/site.rb
class Site < ActiveRecord::Base
  
  ## Non-mass-assignment Attributes: user, subdomain
  ## Mass-Assignment Attributes ##
  attr_accessible :theme, :title
  
  ## Associations ##
  belongs_to :user
  has_many :domains, :dependent => :destroy
  has_many :pages, :dependent => :destroy
  
  ## Validations ##
  validates_presence_of :user
  validates_presence_of :subdomain
  validates_uniqueness_of :subdomain
  
  ## Callbacks ##
  before_create :downcase_subdomain
  
  ## Instance Methods ##
  def downcase_subdomain
    self.subdomain.downcase!
  end
  
  ## Singleton Methods ##
  def self.find_by_domain(domain)
    domain = domain.downcase
    if domain.end_with?(Config::DOMAIN)
      subdomain = domain.chomp(".#{Config::DOMAIN}") #request.subdomain
      Site.where(:subdomain => subdomain).limit(1).first
    else
      Domain.where(:domain => domain).includes(:site).limit(1).first.try(:site)
    end
  end
  
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  
  before_filter :require_authentication!
  before_filter :force_one_site, :only => [:new, :create]
  
  def new
    @site = current_user.build_site
  end
  
  def create
    site = current_user.build_site(params[:site])
    site.title = 'Site' unless site.title
    site.subdomain = current_user.slug ##TODO prevent duplicates (users may have same slug, with different email domains)
    site.theme = 'bootstrap'
    site.save
    
    page = site.pages.create(:title => 'Home', :template => Template.default_filename)
    page.slug = 'home'
    page.default = true
    page.save
    
    redirect_to edit_page_url(:host => "#{site.subdomain}.#{Config::DOMAIN}")
  end
  
  private
  
  def force_one_site
    if current_user.site
      redirect_to root_url, :flash => {:error => 'You already have a site'} ##TODO decide on where to really send them
    end
  end
  
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/sites/_form.html.erb
<%= form_for(@site) do |f| %>
  <% if @site.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@site.errors.count, "error") %> prohibited this site from being saved:</h2>

      <ul>
      <% @site.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sites/edit.html.erb
<h1>Editing site</h1>

<%= render 'form' %>

<%= link_to 'Show', @site %> |
<%= link_to 'Back', sites_path %>

app/views/sites/index.html.erb
<h1>Listing sites</h1>

<table>
  <tr>
    <th>Subdomain</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sites.each do |site| %>
  <tr>
    <td><%= site.subdomain %></td>
    <td><%= link_to 'Show', site %></td>
    <td><%= link_to 'Edit', edit_site_path(site) %></td>
    <td><%= link_to 'Destroy', site, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Site', new_site_path %>

app/views/sites/new.html.erb
<h1>New site</h1>

<%= render 'form' %>

app/views/sites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Subdomain:</b>
  <%= @site.subdomain %>
</p>


<%= link_to 'Edit', edit_site_path(@site) %> |
<%= link_to 'Back', sites_path %>